### ISSUE TITLE
建立訂位資料(包含餐廳、人數、日期、時間)

### ISSUE THREAD

**Issue by dawan680722** [dawan680722/restaurant#18]
建一張新的表，包含餐廳人數、日期、時間

**Comment by peipeitsai** [comment]
[data.zip](https://github.com/dawan680722/restaurant/files/7781347/data.zip)

**Comment by peipeitsai** [comment]
[data.zip](https://github.com/dawan680722/restaurant/files/7781362/data.zip)

**Comment by peipeitsai** [comment]
[data.zip](https://github.com/dawan680722/restaurant/files/7833393/data.zip)

**Comment by peipeitsai** [comment]
[data.zip](https://github.com/dawan680722/restaurant/files/7833459/data.zip)
