### ISSUE TITLE
各頁面設計初稿(自行參考各網站設計)

### ISSUE THREAD

**Issue by dawan680722** [dawan680722/restaurant#8]
將首頁、查詢結果頁面(以食物、餐廳等等)、訂位畫面、訂單完成畫面進行UI位置設計，可以想一下風格大家想統一怎麼樣的~

**Comment by dawan680722** [comment]
分配頁面
藍于婷:訂位畫面
謝語宸:訂單完成
李璦妮:首頁
蔡佩蓉:查詢結果

**Comment by D0845323** [comment]
https://i.imgur.com/UIbLrHL.jpg
